export default {
  introduction: true,
  age: true,
  album: true,
  avatar: true,
  birthday: true,
  birthplace: true,
  bloodtype: true,
  car: true,
  degree: true,
  faith: true,
  focused: true,
  height: true,
  house: true,
  id: true,
  income: true,
  livingPlace: true,
  lunar: true,
  marriage: true,
  nation: true,
  nickname: true,
  realname: true,
  school: true,
  sex: true,
  starsign: true,
  weight: true
}
